settings:
  title: 'Status Page'
  url: 'https://status.tclb.cc' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: tclb-cc # unique identifier
    name: www.tclb.cc
    url: 'https://www.tclb.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: go-tclb-cc
    name: YOURLS
    url: 'https://go.tclb.cc/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false

  - id: dash-tclb-cc
    name: Dashboard tclb.cc
    url: 'https://dash.tclb.cc/login'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: rss-tclb-cc
    name: FreshRSS
    url: 'https://rss.tclb.cc/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false

  - id: grafana-tclb-cc
    name: Grafana
    url: 'https://grafana.tclb.cc/login'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: pihole-tclb-cc
    name: PiHole
    url: 'https://pihole.tclb.cc/admin/api.php'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false

  - id: nextcloud-tclb-cc
    name: Nextcloud
    url: 'https://cloud.tclb.cc/ocs/v2.php/apps/serverinfo/api/v1/info'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
