settings:
  title: 'Status Page'
  url: 'https://status.tclb.cc' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: tclb-cc # unique identifier
    name: www.tclb.cc
    url: 'https://www.tclb.cc/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: pihole-tclb-cc
    name: pihole.tclb.cc
    url: 'https://pihole.tclb.cc/admin/'
    method: GET
    expectStatus: 200

  - id: go-tclb-cc
    name: YOURLS
    url: 'https://go.tclb.cc/'
    method: GET
    expectStatus: 200

  - id: dash-tclb-cc
    name: Dashboard tclb.cc
    url: 'https://dash.tclb.cc/'
    method: GET
    expectStatus: 200
    
  - id: rss-tclb-cc
    name: FreshRSS
    url: 'https://rss.tclb.cc/'
    method: GET
    expectStatus: 200
